import Head from 'next/head';
import TableComponent, { ColumsProps } from '../components/Table';
import styles from '../styles/Home.module.css';
import React, { useMemo, useState } from 'react';
import { Box, Link, Text } from '@chakra-ui/react';

type UserType = {
  id: string;
  username: string;
  name: string;
  email: string;
  role: string;
};

const Home: React.FC = () => {
  const data: UserType[] = [
    {
      id: '1',
      name: 'Iago',
      email: 'iago@gmail.com',
      role: 'admin',
      username: 'iagochaves',
    },
    {
      id: '2',
      name: 'John Doe',
      email: 'john@gmail.com',
      role: 'user',
      username: 'johndoe',
    },
  ];
  const columns = useMemo<ColumsProps<UserType>>(() => {
    return [
      {
        header: 'User',
        columns: [
          {
            key: 'username',
            title: 'USUARIO',
            Cell: ({ username, name }: UserType) => (
              <Box>
                <Link
                  href="#none"
                  color="purple.400"
                  // onMouseEnter={() => handlePrefetchUser(username)}
                >
                  <Text fontWeight="bold">{username}</Text>
                </Link>
                <Text fontSize="sm" color="gray.300">
                  {name}
                </Text>
              </Box>
            ),
          },
          { key: 'email', title: 'EMAIL' },
          { key: 'role', title: 'ROLE' },
        ],
      },
    ];
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TableComponent<UserType>
        data={data}
        groupColumns={columns}
        totalCount={data.length}
        isLoading={false}
        error={false}
      />
    </div>
  );
};

export default Home;
